// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clezevmhryyacxzgtkcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZXpldm1ocnl5YWN4emd0a2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyODkzMDAsImV4cCI6MjA1Mjg2NTMwMH0.6LGpq1ecciSC9rx92hJ1nuHSwdC00IHHpFKKlJsUdw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);